services:
  - type: web
    name: tiebreaker
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    disk: 512
    instanceType: starter
